#!/bin/bash

clear
echo -e "\033[1;31m═══════════════════════════════════════════════════\033[0m"
echo -e "\e[1;46m       🔰 Final Version Script Install VPS 🔰      \e[m "
echo -e "\033[1;31m═══════════════════════════════════════════════════\033[0m"
echo -e "\e[1;31m   🔰 For Debian 9 & 10 64 bit                    \e[m"
echo -e "\e[1;31m   🔰 For Ubuntu 18.04 & Ubuntu 20.04 64bit       \e[m"
echo -e "\e[1;31m   🔰 For VPS with KVM and VMWare virtualization  \e[m"
echo -e "\e[1;31m   🔰 decode gandring bagus satrio                \e[m"
echo -e "\033[1;46m═══════════════════════════════════════════════════\033[0m"
echo -e "\e[1;33m   🔰 Matur Suwun Kagem                           \e[m"
echo -e "\033[1;46m═══════════════════════════════════════════════════\033[0m"
echo -e "\e[1;33m   🔰 ALLAH SWT                                   \e[m"
echo -e "\e[1;33m   🔰 NABI MUHAMMAD SAW                           \e[m"
echo -e "\e[1;33m   🔰 Keluarga Besarku                            \e[m"
echo -e "\e[1;33m   🔰 @rgb_98 & bokirTAMPAN                       \e[m"
echo -e "\e[1;33m   🔰 SenoVPN & geoVPN                            \e[m"
echo -e "\e[1;33m   🔰 Horasss & sukirMAN_gg                       \e[m"
echo -e "\e[1;33m   🔰 Dan semua yang tidak tersebut mohon maaf🙏  \e[m"
echo -e "\033[1;31m═══════════════════════════════════════════════════\033[0m"
echo -e "\e[1;46m          🔰 LUXURY EDITION BY ZEROSSL 🔰          \e[m "
echo -e "\033[1;31m═══════════════════════════════════════════════════\033[0m"
echo ""
read -n 1 -s -r -p "Ketik Bebas Untuk Ke Menu Utama"
menu
